 # Anacreon 6

In [2]:
import numpy as np

In [3]:
#todas as operações funcionam com os vetores.

array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])
array3 = np.array([2, 2])

lista_normal = [1, 1, 1, 1]
lista_normal2 = [4, 2, 6, 2]

print(array1 + array2)
print(lista_normal + lista_normal2)

[5 3 7 3]
[1, 1, 1, 1, 4, 2, 6, 2]


In [ ]:
print(array1 + array3)

In [4]:
import numpy as np

# Vetores com o mesmo tamanho
array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])
array3 = np.array([2, 7])

lista_normal1 = [1, 1, 1, 1]
lista_normal2 = [4, 2, 6, 2] # Substituí os '?' para manter a consistência

# 1. Soma de Vetores (operação matemática elemento a elemento)
print("Soma dos vetores:", array1 + array2)
print("Soma das listas: ", lista_normal1 + lista_normal2)

try:
  # Tenta somar dois vetores de tamanhos incompatíveis (4 e 2)
  soma_vetores_tamanhos_diferentes = array1 + array3
  print("Resultado da soma de vetores de tamanhos diferentes:", soma_vetores_tamanhos_diferentes)

except ValueError as error:
  # Captura o erro esperado e exibe uma mensagem amigável
  print("Não conseguiu somar os vetores de tamanhos diferentes, pois...")
  print(f"Erro: {error}")

Soma dos vetores: [5 3 7 3]
Soma das listas:  [1, 1, 1, 1, 4, 2, 6, 2]
Não conseguiu somar os vetores de tamanhos diferentes, pois...
Erro: operands could not be broadcast together with shapes (4,) (2,) 


In [ ]:
#E se eu quiser somar um número só?

soma_a_todos_os_elementos = np.array([1, 1, 1, 1]) + 20

print(soma_a_todos_os_elementos)

[21 21 21 21]


In [ ]:
#todas as operações funcionam normal
array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])

subtracao = array1 - array2
divisao = array1/array2
multiplicacao = array1 * array2
exponenciacao = array1 ** array2

print(subtracao)
print(divisao)
print(multiplicacao)
print(exponenciacao)

[-3 -1 -5 -1]
[0.25       0.5        0.16666667 0.5       ]
[4 2 6 2]
[1 1 1 1]


In [ ]:
#Operações dentro do próprio vetor

vetor = np.array([1, 4, -4, -1, 2])

print(vetor)
print(vetor.sum())
print(vetor.max())
print(vetor.min())
print(np.abs(vetor))

[ 1  4 -4 -1  2]
2
4
-4
[1 4 4 1 2]


In [ ]:
#Estatisticas descritivas

vetor = np.array([1, 20, -4, -12, 2000])

media = np.mean(vetor)
mediana = np.median(vetor)
desvio_p = np.std(vetor)
var = np.var(vetor)

print(media) #media
print(mediana) #mediana
print(desvio_p) #desvio padrao
print(var) #variancia

401.0
1.0
799.56938410622
639311.2


In [ ]:
#matriz de correlação 

vetor2 = np.array([5, 4, 3, -5, 4])
vetor3 = np.array([2, 6, 7, -5, 1])

correlacao = np.corrcoef((vetor, vetor2, vetor3))

correlacao

array([[ 1.        ,  0.25471058, -0.13247913],
       [ 0.25471058,  1.        ,  0.76783876],
       [-0.13247913,  0.76783876,  1.        ]])

In [ ]:
import numpy as np

# Criação dos dois vetores (arrays NumPy)
array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])

# Realiza as operações matemáticas elemento a elemento
adicao = array1 + array2
subtracao = array1 - array2
multiplicacao = array1 * array2
divisao = (array1 / array2).round(2) 
modulo = array1 % array2 
divisao_inteira = array1 // array2 # Esta é a divisão inteira real
exponenciacao = array1 ** array2

# Imprime os resultados de cada operação
print("Array 1:", array1)
print("Array 2:", array2)
print("-" * 30) # Linha separadora
print("Operação de adição: ", adicao)
print("Operação de subtração: ", subtracao)
print("Operação de multiplicação: ", multiplicacao)
print("Operação de divisão: ", divisao)
print("Operação de Módulo (resto da divisão '%'):", modulo)
print("Operação de divisão inteira '//': ", divisao_inteira)
print("Operação de exponenciação: ", exponenciacao)

Array 1: [1 1 1 1]
Array 2: [4 2 6 2]
------------------------------
Operação de adição:  [5 3 7 3]
Operação de subtração:  [-3 -1 -5 -1]
Operação de multiplicação:  [4 2 6 2]
Operação de divisão:  [0.25 0.5  0.17 0.5 ]
Operação de Módulo (resto da divisão '%'): [1 1 1 1]
Operação de divisão inteira '//':  [0 0 0 0]
Operação de exponenciação:  [1 1 1 1]


In [6]:
import numpy as np

# Cria o vetor (array NumPy) com números positivos e negativos
vetor = np.array([1, 4, -4, -1, 2])


print("Vetor inicial: ", vetor)

print("Soma dos itens do vetor: ", vetor.sum())
print("O maior número do vetor: ", vetor.max())
print("O menor número do vetor: ", vetor.min())
print("Números absolutos do vetor: ", np.abs(vetor))

Vetor inicial:  [ 1  4 -4 -1  2]
Soma dos itens do vetor:  2
O maior número do vetor:  4
O menor número do vetor:  -4
Números absolutos do vetor:  [1 4 4 1 2]


# Exercício

* Exercício 05: Faça um programa que o usuário digite a rentabilidade de ações, com quantas ações o usuário quiser. Transforme essas listas em arrays e devolva pro usuário:

        A média de rentabilidade da carteira.
        O Desvio padrão da carteira.
        A mediana de retornos da carteira.
        O maior retorno.
        O menor retorno.

In [9]:
import numpy as np

vetor = np.array([1, 20, -4, -12, 2000])
media = np.mean(vetor)
mediana = np.median(vetor)
desvio_p = np.std(vetor)
var = np.var(vetor)
max = vetor.max()
min = vetor.min()

print(f"Vetor de dados: {vetor}\n") # Adicionei esta linha para clareza
print(f"A média dos números do vetor é: {media}")
print(f"A mediana dos números do vetor é: {mediana}")
print(f"O desvio padrão dos números do vetor é: {desvio_p}")
print(f"A variância dos números do vetor é: {var}")
print(f"O máximo dos números do vetor é: {max}")
print(f"O minimo dos números do vetor é: {min}")


Vetor de dados: [   1   20   -4  -12 2000]

A média dos números do vetor é: 401.0
A mediana dos números do vetor é: 1.0
O desvio padrão dos números do vetor é: 799.56938410622
A variância dos números do vetor é: 639311.2
O máximo dos números do vetor é: 2000
O minimo dos números do vetor é: -12


In [10]:
import numpy as np

vetor = np.array([1, 20, -4, -12, 2000])
vetor2 = np.array([5, 4, 3, -5, 4])
vetor3 = np.array([2, 6, 7, -5, 1])

# A função np.corrcoef espera uma lista ou tupla de arrays, por isso usamos (vetor, vetor2, vetor3)
correlacao = np.corrcoef((vetor, vetor2, vetor3))

# Imprime a matriz resultante, arredondando os valores para 2 casas decimais
print("A matriz de correlação entre os 3 vetores é:\n")
print(correlacao.round(2))

A matriz de correlação entre os 3 vetores é:

[[ 1.    0.25 -0.13]
 [ 0.25  1.    0.77]
 [-0.13  0.77  1.  ]]


In [7]:
continuar = True

array_rentabilidade = np.array([])

while continuar:

    rent = float(input("Digite uma rentabilidade: "))

    array_rentabilidade = np.append(array_rentabilidade, rent)

    deseja_continuar = str(input("Deseja cadastrar mais rentabilidades? [S/N]")).lower()

    if deseja_continuar != "n" and deseja_continuar != "s":

        invalido = True

        while invalido:

            deseja_continuar = str(input("Por favor, digite um comando válido: [S/N]")).lower()

            if deseja_continuar == "n" or deseja_continuar == "s":

                break

    if deseja_continuar == "n":

        break

media = np.mean(array_rentabilidade)
mediana = np.median(array_rentabilidade)
desvio_padrao = np.std(array_rentabilidade)
rent_max = array_rentabilidade.max()
rent_min = array_rentabilidade.min()

media = "{:.0%}".format(media)
mediana = "{:.0%}".format(mediana)
desvio_padrao = "{:.0%}".format(desvio_padrao)
rent_max = "{:.0%}".format(rent_max)
rent_min = "{:.0%}".format(rent_min)

print("")
print("Aqui estão as estatísticas das rentabilidades:")
print(f"Média: {media}")
print(f"Mediana: {mediana}")
print(f"Desvio padrão: {desvio_padrao}")
print(f"Rentabilidade máxima: {rent_max}")
print(f"Rentabilidade mínima: {rent_min}")

ValueError: could not convert string to float: ''

# Terminus 5 nossa Próxima Parada

Fim do módulo do Numpy! Em Terminus nosso 5 planeta nós iremos abordar o módulo Pandas, a principal biblioteca de análise de dados que existe.
Vamos aprender a puxar cotações, criar médias móveis, tratar dados, ler planilhas de excel e muito mais. Te vejo lá!