# # Anacreon 5

In [2]:
import numpy as np

In [5]:
#juntar dois arrays
import numpy as np

array1 = np.arange(10, 15)
array2 = np.arange(15)

array_completo = np.concatenate([array1, array2])
print("array 1 :",array1)
print("array 2 :",array2)
print("Array Completo :",array_completo)

array 1 : [10 11 12 13 14]
array 2 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Array Completo : [10 11 12 13 14  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8])

# Concatena os três arrays
resultado = np.concatenate((arr1, arr2, arr3))

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)
print("\nResultado da concatenação:")
print(resultado)

Array 1: [1 2 3]
Array 2: [4 5 6]
Array 3: [7 8]

Resultado da concatenação:
[1 2 3 4 5 6 7 8]


In [8]:
#  Concatenando Arrays 2D (Matrizes)
# Aqui é onde o parâmetro axis se torna crucial.
# a) Juntando ao longo das Linhas (axis=0)
# I#sso significa "empilhar" as matrizes uma sobre a outra.

# Regra: Para que isso funcione, as matrizes devem ter o mesmo número de colunas.

matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6]])

# Empilha a matriz_b abaixo da matriz_a
resultado_axis0 = np.concatenate((matriz_a, matriz_b), axis=0)

print("Matriz A (2x2):\n", matriz_a)
print("\nMatriz B (1x2):\n", matriz_b)
print("\nResultado com axis=0 (3x2):\n", resultado_axis0)

Matriz A (2x2):
 [[1 2]
 [3 4]]

Matriz B (1x2):
 [[5 6]]

Resultado com axis=0 (3x2):
 [[1 2]
 [3 4]
 [5 6]]


In [9]:
# b) Juntando ao longo das Colunas (axis=1)
# Isso significa "colar" as matrizes lado a lado.
# Regra: Para que isso funcione, as matrizes devem ter o mesmo número de linhas.

matriz_c = np.array([[1, 2], [3, 4]])
matriz_d = np.array([[7], [8]])

# Junta a matriz_d à direita da matriz_c
resultado_axis1 = np.concatenate((matriz_c, matriz_d), axis=1)

print("Matriz C (2x2):\n", matriz_c)
print("\nMatriz D (2x1):\n", matriz_d)
print("\nResultado com axis=1 (2x3):\n", resultado_axis1)

Matriz C (2x2):
 [[1 2]
 [3 4]]

Matriz D (2x1):
 [[7]
 [8]]

Resultado com axis=1 (2x3):
 [[1 2 7]
 [3 4 8]]


In [3]:
#separando em dois arrays

array_separado1, array_separado2 = np.split(array_completo, [5])

print(array_separado1)
print(array_separado2)

[20 21 22 23 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
import numpy as np

arr = np.arange(12) # Array de 0 a 11
print("Array Original:", arr)

# Dividir em 3 partes iguais
partes = np.split(arr, 3)

print("\nResultado da divisão em 3 partes:")
print(partes)
print("\nTipo do primeiro elemento:", type(partes[0]))

Array Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Resultado da divisão em 3 partes:
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

Tipo do primeiro elemento: <class 'numpy.ndarray'>


In [4]:
#colocar novos dados em um array

#[20 21 22 23 24  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

array_completo = np.append(array_completo, 2000)

array_completo = np.insert(array_completo, 3,  3000)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14 2000]


In [14]:
import numpy as np

arr1d = np.array([1, 2, 3])

# Adicionar um único elemento ao final
novo_arr1 = np.append(arr1d, 4)
print("Adicionando um elemento:", novo_arr1)
novo_arr2 = np.insert(novo_arr1, 2, 99)
print("Inserindo 99 no índice 2:", novo_arr2)
# Saída: [1 2 3 4]

Adicionando um elemento: [1 2 3 4]
Inserindo 99 no índice 2: [ 1  2 99  3  4]


In [12]:
arr1d = np.array([10, 20, 30, 40])

# Inserir o valor 99 na posição de índice 2
novo_arr1 = np.insert(arr1d, 2, 99)
print("Inserindo 99 no índice 2:", novo_arr1)
# Saída: [10 20 99 30 40]

Inserindo 99 no índice 2: [10 20 99 30 40]


In [5]:
#deletar dados de um array

array_completo = np.delete(array_completo, -1)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14]


In [17]:
#reshape
vetor = np.arange(9)
print("Vetor Unidimensional: ",vetor)
array_3x3 = vetor.reshape(3, 3) #isso aqui é util na hora de fazer regressão linear
print("Matriz 3x3 : ",array_3x3)

Vetor Unidimensional:  [0 1 2 3 4 5 6 7 8]
Matriz 3x3 :  [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
import numpy as np

# Array com valores positivos e negativos
dados = np.array([10, -5, 22, -1, 8, -15, 4])
print("Array Original:", dados)

# A condição é "o elemento é menor que 0?"
# Modifica o array original nos locais onde a condição é True
dados[dados < 0] = 0

print("Array Modificado:", dados)

Array Original: [ 10  -5  22  -1   8 -15   4]
Array Modificado: [10  0 22  0  8  0  4]


In [7]:
#trocando números dentro de uma condição

array_inicial = np.array([4, 4, 4, 4, 7, 6, 5, 32, 13, 2, 32, 675, 74, 465])

#como trocar todos os numero menores que 40 por 0?

array_inicial[array_inicial < 40] = 0

print(array_inicial)

[  0   0   0   0   0   0   0   0   0   0   0 675  74 465]


In [20]:
#como ordernar objetos dentro de uma lista?
array_desordenado = np.array([18109, 1249, 314, 10, 9, 2, 25490])

array_crescente = np.sort(array_desordenado)
array_decrescente = -np.sort(-array_desordenado)

print("Array em modo crescente :",array_crescente)
print("Array em modo decrescente :",array_decrescente)

Array em modo crescente : [    2     9    10   314  1249 18109 25490]
Array em modo decrescente : [25490 18109  1249   314    10     9     2]


# Exercício

* Exercício 04: Peça ao usuário digitar o lucro da Petrobras, Vale e Weg. Mostre os lucros em ordem do maior pro menor. (Utilize arrays e ferramentas como append, np.sort, etc)

In [9]:
empresas = np.array(["Weg", "Vale", "Petrobras"])

array_lucros = np.array([])

for empresa in empresas:
    
    lucro = float(input(f"Digite o lucro da {empresa}: "))
    array_lucros = np.append(array_lucros, lucro)

array_lucros = -np.sort(-array_lucros)

print(f'Lucro das empresas, do maior pro menor: {array_lucros}')

Lucro das empresas, do maior pro menor: [23. 20. 10.]


# Anacreon 6

Bom, agora que você já aprendeu a manipular arrays, como a gente pode fazer operações com arrays, que é o mais importante no numpy?
Como calcula média, desvio padrão? No mundo 6 a gente vai descobrir! 