# Anacreon 2

In [3]:
import numpy as np

In [ ]:
#a partir de uma lista ou tupla

lista = [1, 2, 3, 4]

tupla = (1, 2, 3, 4)

array_a_partir_de_lista = np.array(lista)

array_a_partir_de_tupla = np.array(tupla)

print(array_a_partir_de_tupla)

In [ ]:
#usando um range

array_simples = np.arange(10)

array_sequencial = np.arange(10, 100, 10)

array_simples, array_sequencial

In [ ]:
#criando arrays de zeros ou ums

vetor_zero = np.zeros(5)
vetor_um = np.ones(5)

vetor_zero, vetor_um

(array([0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1.]))

In [ ]:
#criando vetores aleatórios

vetor_aleatorio_entre_0_1 = np.random.rand(3, 2)
vetor_aleatorio_inteiro = np.random.randint(low = 0, high = 10, size = 3)
vetor_aleatorio_com_negativos = np.random.uniform(-2, 2, 3)

print(vetor_aleatorio_entre_0_1)
print(vetor_aleatorio_inteiro)
print(vetor_aleatorio_com_negativos)

[[0.86780977 0.27514333]
 [0.710473   0.34251492]
 [0.33814048 0.78214966]]
[8 0 6]
[0.25929168 0.13687392 1.17357021]


In [ ]:
#criando arrays bi ou tridimensionais

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista3 = [7, 8, 9]

array2d = np.array([lista1, lista2])

array3d = np.array([lista1, lista2, lista3])

array2d, array3d

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [ ]:
#criando matrizes

matriz = np.matrix([[20, 30], [90, 80]])

matriz

matrix([[20, 30],
        [90, 80]])

In [ ]:
#listas x numpy

lista_1 = [1, 1, 1, 1]
lista_2 = [1, 1, 1, 1]

print(lista_1 + lista_2)
print(np.array(lista_1) + np.array(lista_2))

[1, 1, 1, 1, 1, 1, 1, 1]
[2 2 2 2]


In [1]:
#teste lista x numpy

import timeit

#listas

tempo_listas = timeit.timeit('''X = range(1000); Y = range(1000); [X[i] + Y[i] for i in range(len(X))]''', 
                             number = 10000)
                                
#vetores

tempo_vetor = timeit.timeit('''X = np.arange(1000);Y = np.arange(1000);X + Y''', number = 10000,
                             setup="import numpy as np")
                                
                             

print(tempo_listas, tempo_vetor)
print(f"Os vetores são {tempo_listas/tempo_vetor} vezes mais rápidos.")
#print("Numpy nesse caso é " + str(t1/t2) + " mais rápido!")

2.1396653020001395 0.08183690499936347
Os vetores são 26.145481699445767 vezes mais rápidos.


# Exercícios

* Exercício 01: Peça pro usuário inputar a cotação de 3 ações. Crie um array de cotações.
* Exercício 02: Peça pro usuário digitar dois números no programa e crie um arrange sequencial entre esse números.
* Exercício 03: Crie um programa que gere numeros aleatórios inteiros entre 0 e 60 e devolva 6 números da mega sena pro usuário. Depois, exiba uma probabilidade aleatória de o usuário sair vencedor. Garanta que sejam 6 números diferentes!

In [4]:
acao1 = float(input("Digite a cotação da primeira ação: "))
acao2 = float(input("Digite a cotação da segunda ação: "))
acao3 = float(input("Digite a cotação da terceira ação: "))

array = np.array([acao1, acao2, acao3])

print(array)

[100. 200. 300.]


In [5]:
inicio_sequencia = float(input("Digite o primeiro número: "))
final_sequencia = float(input("Digite o segundo número: "))

sequencia = np.arange(inicio_sequencia, final_sequencia)

sequencia

array([200., 201., 202., 203., 204., 205., 206., 207., 208., 209., 210.,
       211., 212., 213., 214., 215., 216., 217., 218., 219., 220., 221.,
       222., 223., 224., 225., 226., 227., 228., 229., 230., 231., 232.,
       233., 234., 235., 236., 237., 238., 239., 240., 241., 242., 243.,
       244., 245., 246., 247., 248., 249., 250., 251., 252., 253., 254.,
       255., 256., 257., 258., 259., 260., 261., 262., 263., 264., 265.,
       266., 267., 268., 269., 270., 271., 272., 273., 274., 275., 276.,
       277., 278., 279., 280., 281., 282., 283., 284., 285., 286., 287.,
       288., 289., 290., 291., 292., 293., 294., 295., 296., 297., 298.,
       299.])

In [6]:
lista_numeros = []

lista_numeros.append(np.random.randint(0, 60, 1)[0])

while len(lista_numeros) < 6:

    mega_sena = np.random.randint(0, 60, 1)

    if mega_sena not in lista_numeros:

        lista_numeros.append(mega_sena[0])

probabilidade_vitoria = np.random.rand(1)[0]

print(f"Seguem os números da mega sena: {lista_numeros}. A probabilidade de vitória é de {probabilidade_vitoria}")

Seguem os números da mega sena: [np.int64(41), np.int64(59), np.int64(6), np.int64(33), np.int64(40), np.int64(36)]. A probabilidade de vitória é de 0.13645183798400085


# Anacreon 3

Agora que você já aprendeu sobre como criar vetores, vamos aprender quais características esses vetores possuem através dos seus atributos!
