# Anacreon 4

In [2]:
import numpy as np

In [3]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

vetor2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [3]:
#posições

print(vetor[0])

print(vetor[0:2])

print(vetor[-1])

print(vetor2d[2][0])
print(vetor2d[0][1])

1
[1 2]
9
7
2


In [4]:
import numpy as np

# Matriz 3x4 (3 linhas, 4 colunas)
matriz = np.array([[ 5, 10, 15, 20],  # Linha 0
                   [25, 30, 35, 40],  # Linha 1
                   [45, 50, 55, 60]]) # Linha 2

# Para pegar o número 35:
# Ele está na linha de índice 1 e na coluna de índice 2.
elemento = matriz[1, 2]

print(f"O elemento na posição [1, 2] é: {elemento}")
# Saída: O elemento na posição [1, 2] é: 35

O elemento na posição [1, 2] é: 35


In [5]:
import numpy as np

# Array com registros de temperatura
temperaturas = np.array([22.5, 26.1, 24.9, 28.3, 19.8, 25.0, 30.2, 23.7])

# Passo 1: Criar a máscara booleana
# A condição é: "o elemento é maior que 25?"
mascara_maior_que_25 = temperaturas > 25

print("Array original:")
print(temperaturas)
# Saída: [22.5 26.1 24.9 28.3 19.8 25.  30.2 23.7]

print("\nMáscara Booleana (temperaturas > 25):")
print(mascara_maior_que_25)
# Saída: [False  True False  True False False  True False]

# Passo 2: Aplicar a máscara para filtrar os dados
temps_altas = temperaturas[mascara_maior_que_25]

print("\nTemperaturas filtradas (acima de 25):")
print(temps_altas)
# Saída: [26.1 28.3 30.2]

Array original:
[22.5 26.1 24.9 28.3 19.8 25.  30.2 23.7]

Máscara Booleana (temperaturas > 25):
[False  True False  True False False  True False]

Temperaturas filtradas (acima de 25):
[26.1 28.3 30.2]


In [ ]:
# Matriz 3x3
matriz = np.array([
    [1, 5, 3],
    [8, 2, 9],
    [4, 6, 7]
])

# Filtrar todos os números maiores ou iguais a 5
numeros_altos = matriz[matriz >= 5]

print("\nMatriz original:")
print(matriz)
print("\nNúmeros >= 5 (resultado é um array 1D):")
print(numeros_altos)
# Saída: [5 8 9 6 7]


Matriz original:
[[1 5 3]
 [8 2 9]
 [4 6 7]]

Números >= 5 (resultado é um array 1D):
[5 8 9 6 7]


In [8]:
import numpy as np

# Array com registros de temperatura
temperaturas = np.array([22.5, 26.1, 24.9, 28.3, 19.8, 25.0, 30.2, 23.7])
# Condição 1: temperaturas > 23
# Condição 2: temperaturas < 29
mascara_combinada = (temperaturas > 23) & (temperaturas < 29)

print("\nMáscara Combinada ((temps > 23) & (temps < 29)):")
print(mascara_combinada)
# Saída: [False  True  True  True False False False  True]

temps_moderadas = temperaturas[mascara_combinada]

print("\nTemperaturas moderadas (entre 23 e 29):")
print(temps_moderadas)
# Saída: [26.1 24.9 28.3 23.7]


Máscara Combinada ((temps > 23) & (temps < 29)):
[False  True  True  True False  True False  True]

Temperaturas moderadas (entre 23 e 29):
[26.1 24.9 28.3 25.  23.7]


In [4]:
#filtrando dados

vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

maior_que_5 = vetor[vetor > 5]

somente_par = vetor[vetor % 2 == 0]

igual_a_5 = vetor[vetor == 5]

maior_que_3_menor_que_8 = vetor[ (vetor > 5) & (vetor < 8)] 

print(maior_que_5)
print(somente_par)
print(igual_a_5)
print(maior_que_3_menor_que_8)

[6 7 8 9]
[2 4 6 8]
[5]
[6 7]


# Exercício

Exercício 04: Análise de Retornos com NumPy

Crie um programa que utilize a biblioteca NumPy para realizar as seguintes tarefas:
Entrada: Peça ao usuário para inserir um número inteiro, que representará a quantidade de dias.
Geração de Dados: Crie um array NumPy contendo a quantidade de dias informada. Cada elemento do array deve ser um número de ponto flutuante (float) aleatório, simulando um retorno diário, no intervalo de -1 a 1.

Análise: A partir do array gerado, extraia as seguintes informações:
Um novo array contendo apenas os retornos positivos.
O valor do primeiro retorno da série.
O valor do último retorno da série.

**Saída: Exiba os resultados da análise de forma clara e organizada.**

In [5]:
dias = int(input("Digite quantos retornos devem ser gerados: "))

retorno_aleatorio = np.random.uniform(-1, 1, dias)

retornos_positivos = retorno_aleatorio[retorno_aleatorio > 0]

print(f'''Os retornos positivos são {retornos_positivos} 
        O primeiro retorno é {retornos_positivos[0]} e o último é {retornos_positivos[-1]}''')

Os retornos positivos são [0.26724035 0.40880079 0.39858147 0.18478914 0.64818347] 
        O primeiro retorno é 0.26724035013299496 e o último é 0.6481834670620925


# Anacreon 5

Essas últimas duas aulas foram rápidas e bem simples. Nos mundos 5 e 6 nós vamos mais a fundo no numpy, descobrindo como podemos fazer conta, extrair
estatísticas, juntar arrays, rankear arrays, adicionar e excluir dados e muito mais. No mundo 5 descobrir como manipular esses arrays da melhor forma!