#Atributos de um Array NumPy
Os arrays NumPy possuem vários atributos que fornecem informações sobre sua estrutura e dados.

##dtype: Tipo de Dado dos Elementos
Indica o tipo de dado dos elementos armazenados no array (e.g., int64, float64).

In [ ]:
import numpy as np

In [ ]:
arr_int = np.array([1, 2, 3])
print("Tipo de dado de arr_int:", arr_int.dtype)

arr_float = np.array([1.0, 2.5, 3.0])
print("Tipo de dado de arr_float:", arr_float.dtype)

arr_bool = np.array([True, False, True])
print("Tipo de dado de arr_bool:", arr_bool.dtype)

Tipo de dado de arr_int: int64
Tipo de dado de arr_float: float64
Tipo de dado de arr_bool: bool


##shape: Formato do Array
Retorna uma tupla indicando o número de elementos em cada dimensão.

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("Shape de arr_1d:", arr_1d.shape)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape de arr_2d:", arr_2d.shape) # (linhas, colunas)

Shape de arr_1d: (5,)
Shape de arr_2d: (2, 3)


##size: Número Total de Elementos
Retorna o número total de elementos no array.

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("Size de arr_1d:", arr_1d.size)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Size de arr_2d:", arr_2d.size)

Size de arr_1d: 5
Size de arr_2d: 6


##ndim: Número de Dimensões
Retorna o número de dimensões (eixos) do array. É o mesmo que a dimensão do array, conforme vimos anteriormente.

In [ ]:
arr_scalar = np.array(10)
print("ndim de arr_scalar:", arr_scalar.ndim)

arr_vector = np.array([1, 2, 3])
print("ndim de arr_vector:", arr_vector.ndim)

arr_matrix = np.array([[1, 2], [3, 4]])
print("ndim de arr_matrix:", arr_matrix.ndim)

ndim de arr_scalar: 0
ndim de arr_vector: 1
ndim de arr_matrix: 2


#Conversões de Arrays
Você pode converter o tipo de dado de um array usando o método .astype().

In [ ]:
arr1 = np.array([1.5, 2.7, 3.2])
print(arr1)
print(arr1.dtype)

# Convertendo para int (trunca a parte decimal)
arr2 = arr1.astype(int)
print(arr2)
print(arr2.dtype)

# Convertendo para float
arr3 = np.array([1, 2, 3])

print(arr3)
print(arr3.dtype)

arr4 = arr3.astype(float)
print(arr4)
print(arr4.dtype)

[1.5 2.7 3.2]
float64
[1 2 3]
int64
[1 2 3]
int64
[1. 2. 3.]
float64
