In [ ]:
import numpy as np

In [ ]:
#Gera um número aleatório entre 0 e 1
num = np.random.rand()
print(num)

0.8745761067289681


In [ ]:
#Gerando um array de 1 dimensão com 5 números aleatórios
array_1d = np.random.rand(5)
print(f"Array com 5 números aleatórios entre 0 e 1: {array_1d}")

Array com 5 números aleatórios entre 0 e 1: [0.87699059 0.14284722 0.98075049 0.67628399 0.52066751]


In [ ]:
#Gerando uma matriz 2x3 de números aleatórios entre 0 e 1
matriz_2x3 = np.random.rand(2, 3)
print(f"Matriz 2 x 3 de números aleatórios entre 0 e 1: \n{matriz_2x3}")

Matriz 2 x 3 de números aleatórios entre 0 e 1: 
[[1.54072040e-01 7.05309712e-01 5.45945791e-01]
 [6.25094905e-01 1.61812919e-04 3.39285186e-01]]


In [ ]:
#Gerando números inteiros entre o e 9
num = np.random.randint(10)
print(num)

4


In [ ]:
#Gerando um array de 3 inteiros aleatórios entre 10 e 20
array_inteiros = np.random.randint(10, 21, size=3)
print(f"Array de inteiros aleatórios entre 10 e 20: {array_inteiros}")

Array de inteiros aleatórios entre 10 e 20: [15 11 19]


In [ ]:
#Gerando uma matriz 2x2 de inteiros aleatórios entre 1 e 100
matriz_2x2 = np.random.randint(1, 101, size=(2, 2))
print(f"Matriz 2 x 2 de números aleatórios entre 1 e 100: \n {matriz_2x2}")

Matriz 2 x 2 de números aleatórios entre 1 e 100: 
 [[19 62]
 [91 97]]


In [ ]:
#Escolhendo elementos aleatoriamente de um array existente
array_frutas = np.array(['maçã', 'banana', 'laranja', 'limão', 'abacaxi'])
print(f"Array de frutas: {array_frutas}")

fruta = np.random.choice(array_frutas, size=2)
print(fruta)

Array de frutas: ['maçã' 'banana' 'laranja' 'limão' 'abacaxi']
['maçã' 'maçã']


In [ ]:
arr = np.array([1, 5, 10, 3, 8, 2, 10, 7])
print("Array original:", arr)

Array original: [ 1  5 10  3  8  2 10  7]


In [ ]:
unique_elements = np.unique(arr)
print("\nElementos únicos:", unique_elements)


Elementos únicos: [ 1  2  3  5  7  8 10]


In [ ]:
unique_elements, counts = np.unique(arr, return_counts=True)
print("Elementos únicos e suas contagens:", dict(zip(unique_elements, counts)))

Elementos únicos e suas contagens: {np.int64(1): np.int64(1), np.int64(2): np.int64(1), np.int64(3): np.int64(1), np.int64(5): np.int64(1), np.int64(7): np.int64(1), np.int64(8): np.int64(1), np.int64(10): np.int64(2)}


In [ ]:
# np.any() - Verifica se há ALGUM True
bool_array1 = np.array([False, False, True, False])
bool_array2 = np.array([False, False, False])
print("\nnp.any([False, False, True, False]):", np.any(bool_array1))
print("np.any([False, False, False]):", np.any(bool_array2))


np.any([False, False, True, False]): True
np.any([False, False, False]): False


In [ ]:
# np.all() - Verifica se TODOS são True
bool_array3 = np.array([True, True, True])
bool_array4 = np.array([True, False, True])
print("np.all([True, True, True]):", np.all(bool_array3))
print("np.all([True, False, True]):", np.all(bool_array4))

np.all([True, True, True]): True
np.all([True, False, True]): False


In [ ]:
arr_unsorted = np.array([9, 2, 7, 1, 5, 3])
print("Array não ordenado:", arr_unsorted)

# np.sort() - Retorna uma cópia ordenada
sorted_copy = np.sort(arr_unsorted)
print("Array ordenado (np.sort):", sorted_copy)
print("Array original após np.sort (inalterado):", arr_unsorted) # Original permanece o mesmo

Array não ordenado: [9 2 7 1 5 3]
Array ordenado (np.sort): [1 2 3 5 7 9]
Array original após np.sort (inalterado): [9 2 7 1 5 3]


In [ ]:
# .sort() - Ordena o array no lugar (modifica o original)
arr_inplace_sort = np.array([9, 2, 7, 1, 5, 3])
print("\nArray para sort in-place:", arr_inplace_sort)
arr_inplace_sort.sort()
print("Array após .sort() (modificado):", arr_inplace_sort)


Array para sort in-place: [9 2 7 1 5 3]
Array após .sort() (modificado): [1 2 3 5 7 9]


In [ ]:
# np.argsort() - Retorna os índices que ordenariam
arr_to_argsort = np.array([9, 2, 7, 1, 5, 3])
sorted_indices = np.argsort(arr_to_argsort)
print("\nArray para argsort:", arr_to_argsort)
print("Índices que ordenariam o array:", sorted_indices)


Array para argsort: [9 2 7 1 5 3]
Índices que ordenariam o array: [3 1 5 4 2 0]


In [ ]:
# Ordenando em matrizes (por linha ou coluna)
matrix_unsorted = np.array([[3, 1, 2],
                            [6, 5, 4]])
print("\nMatriz não ordenada:\n", matrix_unsorted)


Matriz não ordenada:
 [[3 1 2]
 [6 5 4]]


In [ ]:
# Ordenar por linha (axis=1)
sorted_by_row = np.sort(matrix_unsorted, axis=1)
print("Matriz ordenada por linha (axis=1):\n", sorted_by_row)

# Ordenar por coluna (axis=0)
sorted_by_column = np.sort(matrix_unsorted, axis=0)
print("Matriz ordenada por coluna (axis=0):\n", sorted_by_column)

Matriz ordenada por linha (axis=1):
 [[1 2 3]
 [4 5 6]]
Matriz ordenada por coluna (axis=0):
 [[3 1 2]
 [6 5 4]]
