#Arrays Numpy

In [ ]:
import numpy as np

In [ ]:
#Para criar um array numpy utilizamos a função array() - Essa função cria um array a partir de uma lista
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

In [ ]:
#Arrays de 2 dimensões (Também conhecido como matriz)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

In [ ]:
#Arrays de 3 dimensões
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3)

In [ ]:
#Criando um array com N dimensões
arr4 = np.array([1, 2, 3, 4], ndmin=7)
4
print(arr4)
print(arr4.ndim)

[[[[[[[1 2 3 4]]]]]]]
7


In [ ]:
#Verificando o número de dimensões de um array
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


##NP Arange - Arrays com Intervalo Definido
Similar à função range() do Python, np.arange() cria arrays com valores dentro de um intervalo especificado.

In [ ]:
# Criando um array de 0 a 20
arr_arange = np.arange(21)
print("Array arange (0 a 20):", arr_arange)

# Criando um array de 2 a 10 com passo de 2
arr_arange_step = np.arange(2, 11, 2)
print("Array arange (2 a 10, passo 2):", arr_arange_step)

Array arange (0 a 20): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array arange (2 a 10, passo 2): [ 2  4  6  8 10]


##Arrays com Espaçamento Uniforme
np.linspace() cria arrays com um número específico de elementos igualmente espaçados dentro de um intervalo.

In [ ]:
# Criando um array com 5 elementos entre 0 e 10 (inclusive)
arr_linspace = np.linspace(0, 10, 5)
print("Array linspace (0 a 10, 5 elementos):", arr_linspace)

# Exemplo com mais elementos
arr_linspace_more = np.linspace(1, 2, 10)
print("Array linspace (1 a 2, 10 elementos):", arr_linspace_more)

Array linspace (0 a 10, 5 elementos): [ 0.   2.5  5.   7.5 10. ]
Array linspace (1 a 2, 10 elementos): [1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


##Arrays de Zeros
Cria um array preenchido com zeros. Útil para inicializar arrays.

In [ ]:
# Criando um array 1D de 5 zeros
zeros_1d = np.zeros(5)
print("Array de zeros 1D:", zeros_1d)

# Criando um array 2D (3 linhas, 4 colunas) de zeros
zeros_2d = np.zeros((3, 4))
print("Array de zeros 2D:\n", zeros_2d)

##Arrays de Uns
Similar a np.zeros(), cria um array preenchido com uns.

In [ ]:
# Criando um array 1D de 4 uns
ones_1d = np.ones(4)
print("Array de uns 1D:", ones_1d)

# Criando um array 2D (2 linhas, 3 colunas) de uns
ones_2d = np.ones((2, 3))
print("Array de uns 2D:\n", ones_2d)

Array de uns 1D: [1. 1. 1. 1.]
Array de uns 2D:
 [[1. 1. 1.]
 [1. 1. 1.]]
