#Operações Elementares (Aritméticas)
As operações aritméticas com arrays NumPy são realizadas elemento a elemento.

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Soma
soma = arr1 + arr2
print("Soma:", soma)

# Subtração
subtracao = arr2 - arr1
print("Subtração:", subtracao)

# Multiplicação (elemento a elemento)
multiplicacao = arr1 * arr2
print("Multiplicação (elemento a elemento):", multiplicacao)

# Divisão (elemento a elemento)
divisao = arr2 / arr1
print("Divisão (elemento a elemento):", divisao)

# Potência
potencia = arr1 ** 2
print("Potência (arr1 ao quadrado):", potencia)

#Operações com Escalar
Quando você realiza uma operação entre um array e um valor escalar (um único número), o NumPy aplica essa operação a cada elemento do array.

In [ ]:
arr = np.array([10, 20, 30, 40])
escalar = 5

# Soma com escalar
soma_escalar = arr + escalar
print("Soma com escalar:", soma_escalar)

# Multiplicação com escalar
mult_escalar = arr * scalar
print("Multiplicação com escalar:", mult_escalar)

#Broadcasting
Broadcasting é a capacidade do NumPy de tratar arrays com diferentes shapes durante operações aritméticas. Ele permite que arrays menores sejam "esticados" para combinar com o shape de arrays maiores, de modo que a operação elemento a elemento possa ser realizada.

In [ ]:
import numpy as np

In [ ]:
arr_a = np.array([[1, 2, 3],
                  [4, 5, 6]]) # Shape (2, 3)

arr_b = np.array([10, 20, 30]) # Shape (3,)

# arr_b é "broadcast" para corresponder ao número de linhas de arr_a
# [10, 20, 30]
# [10, 20, 30]
resultado_broadcasting = arr_a + arr_b
print("Resultado do Broadcasting:\n", resultado_broadcasting)

# Outro exemplo de broadcasting
arr_c = np.array([[100],
                  [200]]) # Shape (2, 1)

resultado_broadcasting_2 = arr_a + arr_c
print("Resultado do Broadcasting 2:\n", resultado_broadcasting_2)


Resultado do Broadcasting:
 [[11 22 33]
 [14 25 36]]
Resultado do Broadcasting 2:
 [[101 102 103]
 [204 205 206]]
