# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [ ]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(media_salarial)

3714.285714285714


In [ ]:
# Identificar funcionários com salários acima da média


(array([2, 4, 5, 6], dtype=int64),)


In [ ]:
# dar bônus de 10% para os funcionários com salários abaixo da média


[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [ ]:
# filtrar os salários entre 3000 e 4500 com where


(array([0, 1, 2, 4, 5], dtype=int64),)


In [ ]:
# filtrar os salários abaixo de 3000 ou acima de 4500 com where


(array([3, 4, 6], dtype=int64),)
